baseurl: "" # repo is jongjyh.github.io so baseurl is empty

# Build settings
markdown: kramdown
plugins:
  - jekyll-email-protect

timezone: Asia/Shanghai

collections:
  - publications
  - news
  - showcase
  - posts
